CREATE TABLE Users (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    balance DECIMAL(12,2) NOT NULL DEFAULT 0
);

CREATE TABLE Sellers (
    id INT PRIMARY KEY,
    FOREIGN KEY (id) REFERENCES Users(id)
);

CREATE TABLE Category (
    name VARCHAR(255) NOT NULL PRIMARY KEY
);

CREATE TABLE Products (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    creator_id INT NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL,
    category VARCHAR(255) NOT NULL,
    description VARCHAR(2500) NOT NULL,
    image BYTEA,
    FOREIGN KEY (creator_id) REFERENCES Sellers(id),
    FOREIGN KEY (category) REFERENCES Category(name)
);

CREATE TABLE Inventory (
    seller_id INT NOT NULL,
    pid INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    quantity INT NOT NULL,
    PRIMARY KEY(seller_id, pid),
    FOREIGN KEY (seller_id) REFERENCES Sellers(id),
    FOREIGN KEY (pid) REFERENCES Products(id)
);

CREATE TABLE Orders (
    id INT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uid INT NOT NULL,
    status VARCHAR(255) NOT NULL DEFAULT 'Pending',
    timestamp timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    FOREIGN KEY (uid) REFERENCES Users(id)
);

CREATE TABLE SavedItems (
    uid INT NOT NULL,
    seller_id INT NOT NULL,
    pid INT NOT NULL,
    PRIMARY KEY (uid, seller_id, pid),
    num_items INT NOT NULL DEFAULT 1,
    in_cart BOOLEAN DEFAULT TRUE,
    time_added timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    FOREIGN KEY (uid)  REFERENCES Users(id),
    FOREIGN KEY (seller_id) REFERENCES Sellers(id),
    FOREIGN KEY (pid) REFERENCES Products(id)
);

CREATE TABLE Purchases(
    order_id INT NOT NULL,
    seller_id INT NOT NULL,
    pid INT NOT NULL,
    num_items INT NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    time_purchased timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    time_updated timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    PRIMARY KEY (order_id, seller_id, pid),
    FOREIGN KEY (order_id) REFERENCES Orders(id),
    FOREIGN KEY (seller_id) REFERENCES Sellers(id),
    FOREIGN KEY (pid) REFERENCES Products(id)
);

